version: '3.8'

services:
  web:
    build: .
    container_name: orion-web
    ports:
      - "8000:8000"
    environment:
      - DOCKERIZED=true  # 🔹 Повідомляємо Django, що це Docker
    volumes:
      - ./sqlite_data:/app/sqlite_data  # ✅ Правильно

