# Generated by Django 5.2.1 on 2025-05-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_notes_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В очікуванні'), ('completed', 'Виконано'), ('canceled', 'Скасовано')], default='pending', max_length=50),
        ),
    ]
